import argparse#, argcomplete
from GrassSV.Scripts import roi_statistics

TEXT = 'roi_statistics'

def add_subparser(subparsers):
    find_sv = subparsers.add_parser(TEXT, help='confronts found regions with generated mutations',
                                    description="Confront found regions with generated mutations, and calculate useful statistics about them. "
                                                "Specify path to at least one class of structural variation. "
                                                "Supported format for generated mutations is currently tsv generated by rsvsim. ")
    find_sv.add_argument('regions', type=str, metavar='regions_path')
    find_sv.add_argument('-D', '--deletions', type=str, metavar='path')
    find_sv.add_argument('-I', '--insertions', type=str, metavar='path')
    find_sv.add_argument('-d', '--duplications', type=str, metavar='path')
    find_sv.add_argument('-i', '--inversions', type=str, metavar='path')
    find_sv.add_argument('-t', '--translocations', type=str, metavar='path')

def action(args):
    roi_statistics.run(roi_path=args.regions,
                       deletion_path=args.deletions,
                       insertion_path=args.insertions,
                       inversion_path=args.inversions,
                       translocation_path=args.translocations,
                       duplication_path=args.duplications)
