import argparse#, argcomplete

from GrassSV.Scripts import generated_mutations_to_bed

TEXT = 'rsvsim2bed'


def add_subparser(subparsers):
    csv2bed = subparsers.add_parser(TEXT, help='converts sequences from rsvsims\'s csv format to bed',
                                    description="Convert mutations generated by rsvsims from csv format to bed format, for later visualization")
    csv2bed.add_argument('-o', '--output', type=str, metavar='path', help='output file', required=True)
    csv2bed.add_argument('-i', '--input', type=str, metavar='path', nargs='+', help='input file[files]', action='store',
                         default='', required=True)


def action(args):
    print(args.csv)
    generated_mutations_to_bed.run(bed_path=args.bed,
                                   csv_paths=args.csv)
